name: Example GitHub Actions Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub context information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"

      - name: Print environment variables
        run: |
          echo "Home Directory: ${{ env.HOME }}"
          echo "Runner OS: ${{ runner.os }}"
